# Generated by Django 4.0.4 on 2022-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gratuidade', models.CharField(blank=True, max_length=100)),
                ('nome', models.CharField(db_index=True, max_length=70, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('conta', models.CharField(blank=True, max_length=100)),
                ('vantagens', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'planos',
                'ordering': ('nome',),
            },
        ),
    ]
